import {
  type AnyTableFunctionSource,
  type AnyUnnestSource,
  type AnyValuesSource,
  type CapabilitiesOfPlan,
  type CompletePlan,
  type DialectCompatiblePlan,
  type DerivedSourceRequiredError,
  type CteSource,
  type EffectiveNullability,
  type ExpressionInput,
  type ExpressionOutput,
  type GroupByInput,
  type MergeCapabilities,
  type MergeCapabilityTuple,
  type HavingPredicateInput,
  type OrderDirection,
  type OutputOfSelection,
  type MutationTargetLike,
  type NumericExpressionInput,
  type PredicateInput,
  type QueryCapability,
  type QueryPlan,
  type QueryRequirement,
  type SetCompatiblePlan,
  type SetCompatibleRightPlan,
  type SetOperator,
  type QueryStatement,
  type ResultRow,
  type ResultRows,
  type RuntimeResultRow,
  type RuntimeResultRows,
  type SchemaTableLike,
  type SourceCapabilitiesOf,
  type SourceRequiredOf,
  type SourceRequirementError,
  type StatementOfPlan,
  type StringExpressionInput
} from "../internal/query.js"
import {
  type PublicNonStructuredFromApi,
  type PublicStructuredFromConstraint,
  type PublicStructuredFromResult,
  type as mysqlType,
  values,
  unnest,
  select,
  insert,
  from as dslFrom
} from "./internal/dsl.js"

export {
  literal,
  column,
  cast,
  eq,
  neq,
  lt,
  lte,
  gt,
  gte,
  isNull,
  isNotNull,
  like,
  ilike,
  regexMatch,
  regexIMatch,
  regexNotMatch,
  regexNotIMatch,
  and,
  or,
  not,
  all,
  any,
  case_ as case,
  match,
  in_ as in,
  notIn,
  between,
  contains,
  containedBy,
  overlaps,
  exists,
  isDistinctFrom,
  isNotDistinctFrom,
  excluded,
  as,
  with_ as with,
  withRecursive,
  lateral,
  scalar,
  inSubquery,
  compareAny,
  compareAll,
  generateSeries,
  values,
  unnest,
  select,
  returning,
  onConflict,
  insert,
  update,
  upsert,
  delete_ as delete,
  truncate,
  merge,
  transaction,
  commit,
  rollback,
  savepoint,
  rollbackTo,
  releaseSavepoint,
  createTable,
  dropTable,
  createIndex,
  dropIndex,
  union,
  unionAll,
  intersect,
  intersectAll,
  except,
  exceptAll,
  where,
  having,
  innerJoin,
  leftJoin,
  rightJoin,
  fullJoin,
  crossJoin,
  distinct,
  distinctOn,
  limit,
  offset,
  lock,
  orderBy,
  groupBy
} from "./internal/dsl.js"
import type * as Expression from "../internal/scalar.js"
export { mysqlType as type }

type MysqlMutationValueInput<Value> =
  | Value
  | Expression.Scalar<Value, Expression.DbType.Any, Expression.Nullability, "mysql", Expression.ScalarKind, Expression.BindingId>

export type MutationInputOf<Shape> = {
  readonly [K in keyof Shape]: MysqlMutationValueInput<Shape[K]>
}

type StructuredSource = AnyValuesSource | AnyUnnestSource | AnyTableFunctionSource

type StructuredFromApi = <CurrentSource extends StructuredSource>(
  source: CurrentSource
) => <PlanValue extends QueryPlan<any, any, any, any, any, any, any, any, any, any>>(
  plan: PlanValue & PublicStructuredFromConstraint<PlanValue, CurrentSource, "mysql">
) => PublicStructuredFromResult<PlanValue, CurrentSource, "mysql">

export const from: StructuredFromApi & PublicNonStructuredFromApi = dslFrom as StructuredFromApi & PublicNonStructuredFromApi

export type {
  CapabilitiesOfPlan,
  CompletePlan,
  DialectCompatiblePlan,
  DerivedSourceRequiredError,
  CteSource,
  EffectiveNullability,
  ExpressionInput,
  ExpressionOutput,
  GroupByInput,
  MergeCapabilities,
  MergeCapabilityTuple,
  HavingPredicateInput,
  OrderDirection,
  OutputOfSelection,
  MutationTargetLike,
  NumericExpressionInput,
  PredicateInput,
  QueryCapability,
  QueryPlan,
  QueryStatement,
  QueryRequirement,
  SetCompatiblePlan,
  SetCompatibleRightPlan,
  SetOperator,
  ResultRow,
  ResultRows,
  RuntimeResultRow,
  RuntimeResultRows,
  SchemaTableLike,
  SourceCapabilitiesOf,
  SourceRequiredOf,
  SourceRequirementError,
  StatementOfPlan,
  StringExpressionInput
}

export { union_query_capabilities } from "../internal/query.js"
