import { mkdir } from "node:fs/promises"

import { mysqlErrorCatalogBySymbol } from "../src/mysql/errors/catalog.ts"
import { postgresErrorCatalog } from "../src/postgres/errors/catalog.ts"

const outRoot = new URL("../src/", import.meta.url)

const banner = `// Generated by packages/querybuilder/scripts/generate-error-classes.ts\n// Do not edit by hand.\n`

const sortEntries = <A>(entries: readonly A[], keyOf: (value: A) => string): A[] =>
  [...entries].sort((left, right) => keyOf(left).localeCompare(keyOf(right)))

const toPascalCase = (value: string): string =>
  value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((segment) => segment[0]!.toUpperCase() + segment.slice(1).toLowerCase())
    .join("")

const generateMysql = async () => {
  const descriptors = sortEntries(Object.entries(mysqlErrorCatalogBySymbol), ([symbol]) => symbol)

  const lines: string[] = [
    banner.trimEnd(),
    "",
    'import type { MysqlErrorSymbol } from "./catalog.js"',
    'import { MysqlKnownErrorClass, type MysqlKnownErrorArgs, type MysqlKnownErrorBase } from "./types.js"',
    ""
  ]

  for (const [symbol, descriptor] of descriptors) {
    lines.push(`export class ${symbol} extends MysqlKnownErrorClass {`)
    lines.push(`  override readonly _tag = ${JSON.stringify(descriptor.tag)} as const`)
    lines.push(`  override readonly category = ${JSON.stringify(descriptor.category)} as const`)
    lines.push(`  override readonly number = ${JSON.stringify(descriptor.number)} as const`)
    lines.push(`  override readonly symbol = ${JSON.stringify(symbol)} as const`)
    if (descriptor.sqlState === undefined) {
      lines.push(`  override readonly documentedSqlState = undefined`)
    } else {
      lines.push(`  override readonly documentedSqlState = ${JSON.stringify(descriptor.sqlState)} as const`)
    }
    lines.push(`  override readonly messageTemplate = ${JSON.stringify(descriptor.messageTemplate)} as const`)
    lines.push("}")
  }

  lines.push("")
  lines.push("export interface MysqlKnownErrorInstancesBySymbol {")
  for (const [symbol] of descriptors) {
    lines.push(`  readonly ${JSON.stringify(symbol)}: ${symbol}`)
  }
  lines.push("}")
  lines.push("")
  lines.push("export const mysqlKnownErrorClassesBySymbol: Record<MysqlErrorSymbol, new (args: MysqlKnownErrorArgs) => MysqlKnownErrorBase> = {")
  for (const [symbol] of descriptors) {
    lines.push(`  ${JSON.stringify(symbol)}: ${symbol},`)
  }
  lines.push("}")
  lines.push("")
  lines.push("export type KnownMysqlErrorBySymbol<Symbol extends MysqlErrorSymbol> =")
  lines.push("  MysqlKnownErrorInstancesBySymbol[Symbol]")
  lines.push("")

  await Bun.write(new URL("./mysql/errors/generated.ts", outRoot), `${lines.join("\n")}\n`)
}

const generatePostgres = async () => {
  const descriptors = sortEntries(Object.entries(postgresErrorCatalog), ([code]) => code)
  const usedNames = new Set<string>()
  const classNames = new Map<string, string>()

  for (const [code, descriptor] of descriptors) {
    const baseName = `${toPascalCase(descriptor.condition)}Error`
    const className = usedNames.has(baseName) ? `${baseName}_${code}` : baseName
    usedNames.add(className)
    classNames.set(code, className)
  }

  const lines: string[] = [
    banner.trimEnd(),
    "",
    'import type { PostgresSqlStateCode } from "./catalog.js"',
    'import { PostgresKnownErrorClass, type PostgresKnownErrorArgs, type PostgresKnownErrorBase } from "./types.js"',
    ""
  ]

  for (const [code, descriptor] of descriptors) {
    const className = classNames.get(code)!
    lines.push(`export class ${className} extends PostgresKnownErrorClass {`)
    lines.push(`  override readonly _tag = ${JSON.stringify(descriptor.tag)} as const`)
    lines.push(`  override readonly code = ${JSON.stringify(code)} as const`)
    lines.push(`  override readonly condition = ${JSON.stringify(descriptor.condition)} as const`)
    lines.push(`  override readonly classCode = ${JSON.stringify(descriptor.classCode)} as const`)
    lines.push(`  override readonly className = ${JSON.stringify(descriptor.className)} as const`)
    lines.push(`  override readonly primaryFields = ${JSON.stringify(descriptor.primaryFields)} as const`)
    lines.push("}")
  }

  lines.push("")
  lines.push("export interface PostgresKnownErrorInstancesByCode {")
  for (const [code] of descriptors) {
    lines.push(`  readonly ${JSON.stringify(code)}: ${classNames.get(code)!}`)
  }
  lines.push("}")
  lines.push("")
  lines.push("export const postgresKnownErrorClassesByCode: Record<PostgresSqlStateCode, new (args: PostgresKnownErrorArgs) => PostgresKnownErrorBase> = {")
  for (const [code] of descriptors) {
    lines.push(`  ${JSON.stringify(code)}: ${classNames.get(code)!},`)
  }
  lines.push("}")
  lines.push("")
  lines.push("export type KnownPostgresErrorByCode<Code extends PostgresSqlStateCode> =")
  lines.push("  PostgresKnownErrorInstancesByCode[Code]")
  lines.push("")

  await Bun.write(new URL("./postgres/errors/generated.ts", outRoot), `${lines.join("\n")}\n`)
}

await mkdir(new URL("./mysql/errors/", outRoot), { recursive: true })
await mkdir(new URL("./postgres/errors/", outRoot), { recursive: true })

await generateMysql()
await generatePostgres()
