import type * as Expression from "./expression.ts"
import type { FamilyOfDbType } from "./datatypes/lookup.ts"

export type CoercionKind =
  | "text"
  | "numeric"
  | "boolean"
  | "date"
  | "time"
  | "timestamp"
  | "binary"
  | "interval"
  | "uuid"
  | "json"
  | "xml"
  | "bit"
  | "identifier"
  | "network"
  | "spatial"
  | "textsearch"
  | "range"
  | "multirange"
  | "array"
  | "record"
  | "domain"
  | "enum"
  | "set"
  | "money"
  | "null"
  | `other:${string}`

export type CoercionKindOf<Db extends Expression.DbType.Any> = FamilyOfDbType<Db>
