import {
  type as standardType
} from "../internal/standard-dsl.js"
import type * as Expression from "../internal/scalar.js"

export {
  literal,
  column,
  cast,
  eq,
  neq,
  lt,
  lte,
  gt,
  gte,
  isNull,
  isNotNull,
  like,
  ilike,
  collate,
  regexMatch,
  regexIMatch,
  regexNotMatch,
  regexNotIMatch,
  and,
  or,
  not,
  all,
  any,
  case_ as case,
  match,
  in_ as in,
  notIn,
  between,
  contains,
  containedBy,
  overlaps,
  exists,
  isDistinctFrom,
  isNotDistinctFrom,
  excluded,
  as,
  with_ as with,
  withRecursive,
  lateral,
  scalar,
  inSubquery,
  compareAny,
  compareAll,
  values,
  unnest,
  select,
  returning,
  onConflict,
  insert,
  update,
  upsert,
  delete_ as delete,
  truncate,
  merge,
  transaction,
  commit,
  rollback,
  savepoint,
  rollbackTo,
  releaseSavepoint,
  createTable,
  dropTable,
  createIndex,
  dropIndex,
  union,
  unionAll,
  intersect,
  intersectAll,
  except,
  exceptAll,
  where,
  having,
  from,
  innerJoin,
  leftJoin,
  rightJoin,
  fullJoin,
  crossJoin,
  distinct,
  limit,
  offset,
  lock,
  orderBy,
  groupBy,
  lower,
  upper,
  concat,
  coalesce,
  call,
  count,
  max,
  min,
  over,
  rowNumber,
  rank,
  denseRank
} from "../internal/standard-dsl.js"

export { standardType as type }
export { union_query_capabilities } from "../internal/query.js"

export type MutationInputOf<Shape> = {
  readonly [K in keyof Shape]:
    | Shape[K]
    | Expression.Scalar<Shape[K], Expression.DbType.Any, Expression.Nullability, "standard", Expression.ScalarKind, Expression.BindingId>
}

export type {
  AnyTableFunctionSource,
  AnyUnnestSource,
  AnyValuesSource,
  CapabilitiesOfPlan,
  CompletePlan,
  CteSource,
  DialectCompatiblePlan,
  DerivedSourceRequiredError,
  EffectiveNullability,
  ExpressionInput,
  ExpressionOutput,
  GroupByInput,
  HavingPredicateInput,
  MergeCapabilities,
  MergeCapabilityTuple,
  MutationTargetLike,
  NumericExpressionInput,
  OrderDirection,
  OutputOfSelection,
  PredicateInput,
  QueryCapability,
  QueryPlan,
  QueryRequirement,
  QueryStatement,
  ResultRow,
  ResultRows,
  RuntimeResultRow,
  RuntimeResultRows,
  SchemaTableLike,
  SetCompatiblePlan,
  SetCompatibleRightPlan,
  SetOperator,
  SourceCapabilitiesOf,
  SourceRequiredOf,
  SourceRequirementError,
  StatementOfPlan,
  StringExpressionInput
} from "../internal/query.js"
